# -*- mode:ruby -*-

source :rubygems

#gem "sshkit", "=1.3.0"
gem "unicorn", "=4.8.0"
gem "rack"
gem "json"
gem "haml"
gem "sass"
gem "activesupport", "=3.2.14"
gem "mime-types", "=1.25.1"
gem "pg"
gem "sequel", "=3.44.0"
gem 'ramaze'
gem "mongrel", '>= 1.2.0.pre2'
gem "faker"
gem "RedCloth" #, "=2.15.0"
gem "bacon"
gem "dalli"
gem "i18n", "=0.6.9"
gem "highline"
gem "term-ansicolor", "=1.0.7", :require => "term/ansicolor"
gem "builder"
gem "capistrano", "=2.15.5"
gem "subcommand"
gem "rmagick", :require => "RMagick" #, "=2.13.2", :require => "RMagick"
gem "tlsmail"
gem "execjs", "=2.0.2"
gem "uglifier"
gem "rdiscount"
gem "koala"
gem "carrierwave"
gem 'carrierwave-sequel', :require => 'carrierwave/sequel'
gem "calendar_helper"
gem "twitter"
gem "feedjira"
gem "redcarpet"
gem "truncate_html"
gem "nokogiri"
gem "flickraw"
